### ISSUE TITLE
Due date for final loadouts

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/SF-loadouts#1]
1 January is the deadline...I am asking that all parties involved in the other discussion aka [OP_Red_November](https://github.com/Spearhead-Gaming-Milsim/OP_Red_November/issues/7) take a look in here so that we can get this completed without further **_red ass_** commentary. In other words all parties are correct they need to find common ground. I apologize for having been unavailable today but family comes first 100% of the time for me. I am also sick as a dog with headaches, vertigo and other issues from an ear infection.

**Comment by Yakavetta** [comment]
This isn't working out Nichols. I'm explaining our SOP's and your boy has decided he doesn't give even care about the new structure. 

Put him in his place, like Dodds instructed. This is done.

**Comment by jerkinmerkin** [comment]
Okay @Yakavetta, @SHG-LIM, @FoxKilo, @coachwn, let's talk.  First I'd like to apologize for my remarks last night.  I had one too many margs and when I saw that email I lost my cool.  I apologize for that.  I have always been in good relations with SOF until the events of the last week.  Furlong, Lim, you have always been a great source of help and I don't want to end.  

Here's why this has been such a headache for me.  I have put in hundred of man hours of my free time to make missions.  I enjoy it, or else I wouldn't be doing it.  But the hardest thing about making missions for this community is how it seems that every 3 months we completely restructure it, forcing me to re-do many of the slots and loadouts.  That happened to Queen's Stallions TWICE.  That is why I have been struggling to adjust to the new system, because I'm burnt out on re-doing it so many times.  So there's that variable.  Then, when Hauser's mission went to shit, mine was put to the front of the line and given a deadline for launch.  SH had been without a mission for a month, so I was under a lot of pressure to get it right.  For some reason, persistence broke and we had trouble narrowing it down.  My time before launch was dedicated to fixing that as I saw it as the most pressing issue.  Fox came to me with your loadouts at the wrong time, which required adjusting once again for the new structure.  Contrary to what you may think, I did indeed look at your SOP and make your load out to what I feel is 90% of what you wanted.  I worked closely with FoxKilo to get that as right as I could at the time.  Hell, I spent days getting the UAV working for you.  Then, just days before launch, Furlong, I felt you went over my head when you injected a loadout script into the mission which did not fit the timeframe, setting, or scenario.  That was like a big middle finger to all my hard work to get the mission running.  I know ScottyZ will let you do that, but I won't allow it.  Here's what I ask of you now that persistence is up and running, get on the mission.  Examine the load outs.  I think you'll actually be pleasantly surprised to see that I actually worked hard to fit your loadouts into the scenario.  Then let's you and I sit down and talk about what we can do to alleviate and discrepancies that remain.

Now, here's a word about my missions.  I like to make missions that are different and fun.  The SOP laid out in SOF seems rigidly based around a modern US special forces group.  I do not plan on making missions which involve a unit such as that, we've already played too many missions like that, and I'll leave that up to other mission makers to make more.  Someday I will, but not in the near future.  Based on that, we're going to have disagreements over the loadouts.  Just telling me to read your SOP is not constructive whatsoever.  I will do my best to adjust your SOP to fit the scenario and setting.  Any disagreements you and I will discuss and see what we can alleviate.

OP Red November is inspired by the Yugoslav Wars.  I have purposefully made it a fictional country and fictional units as to not offend anyone.  The mission has been in the WIP section for over a month now, and Furlong you even commented on it.  I saw no objections.  If you have objections now let's talk out it.  The loadouts you see is a first draft.  As I have previously said, I'm having trouble integrating the breacher and UAV specialist into the mission.  Let's work together to find a solution.

FoxKilo, you've been a great help with mission testing, but obviously things are getting miscommunicated when I use you as a go between between me and Furlong.  Let's avoid SOF issues from this point forward and just concentrate on general mission bugs.  Furlong, let's you and I get together on TS after the holidays and work out loadouts.  I want to squash this and go back to having everyone enjoying the missions again.

I hope you all can understand everything I'm getting off my chest here.  I also hope everyone has a Happy Holidays.  I'll see you all when I get back.

**Comment by coachwn** [comment]
Well thanks @jerkinmerkin I hadn't seen this until @FoxKilo just linked it to me. Jerkin I am looking at the @SH_CDF file you gave me; this afternoon if I get time. As I understand it there are flares where there should be smoke grenades right now. I hope I get some time here to work on this without interruptions and **maybe** I can have it updated for the mission by tomorrow; if not then we will have it shortly afterwards.

**Comment by Yakavetta** [comment]
This issue is resolved.
